mount /dev/sda2 /media/games

#### Visuals ####
xrandr --output DisplayPort-0 --mode 2560x1440 --rate 240 &
xrandr --output DisplayPort-1 --mode 2560x1440 --rate 165 &
feh --bg-scale /home/ryan/Pictures/lenext.jpg &
picom -f &
slstatus & 
dunst &
wal -R &
#### loop ####
while true; do
	dwm >/dev/null  2>&1
done

#### DWM ####
exec dwm

sleep 10 
backgroundchange.sh
